doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            EmployeeIdType: App\Payroll\Infrastructure\Persistence\Doctrine\Types\EmployeeIdType
            DepartmentIdType: App\Payroll\Infrastructure\Persistence\Doctrine\Types\DepartmentIdType
            AdditionalSalaryType: App\Payroll\Infrastructure\Persistence\Doctrine\Types\AdditionalSalaryType
            MoneyType: App\Payroll\Infrastructure\Persistence\Doctrine\Types\MoneyType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Payroll:
                type: xml
                prefix: 'App\Payroll\Domain'
                dir: '%kernel.project_dir%/src/Payroll/Infrastructure/Persistence/Doctrine/Mapping'
                is_bundle: false
